/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Matth
 * Created: 31-lug-2016
 */


CREATE TABLE Acquirente
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    nome VARCHAR(20),
    cognome VARCHAR(20), 
    username VARCHAR(20),
    password VARCHAR(20),
    saldo_id INTEGER,
    FOREIGN KEY (saldo_id) REFERENCES saldo(id)
);

CREATE TABLE Venditore
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    nome VARCHAR(20),
    cognome VARCHAR(20), 
    username VARCHAR(20),
    password VARCHAR(20),
    saldo_id INTEGER,
    FOREIGN KEY (saldo_id) REFERENCES saldo(id)
);

CREATE TABLE Oggetti
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    nome VARCHAR(20),
    descrizione VARCHAR(400), 
    url VARCHAR(200),
    quantita INTEGER,
    prezzo DOUBLE PRECISION,
    venditore_id INTEGER,
    FOREIGN KEY (venditore_id) REFERENCES venditore(id)
);
